In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import MinMaxScaler

In [3]:
df = pd.read_csv('/content/drive/MyDrive/Certificates/Colab Notebooks/Adanet/3_channel_3_class_meregd.csv')
df.drop('Unnamed: 0',axis=1,inplace=True) 
df

mean_r      std_r  min_r  max_r       var_r      mean_g      std_g  \
0    234.351562  19.891146  144.0  248.0  395.657654  171.654297  28.922405   
1    240.658203  13.831165  160.0  248.0  191.301147  190.408203  29.130186   
2    242.902344  11.503322  160.0  248.0  132.326401  198.523438  29.175911   
3    239.787109  14.744755  152.0  248.0  217.407806  186.863281  29.279314   
4    246.402344   6.019032  176.0  248.0   36.228745  224.769531  24.001497   
..          ...        ...    ...    ...         ...         ...        ...   
216  237.068359  16.921211  120.0  248.0  286.327362  211.224609  27.665842   
217  235.962891  17.905966  128.0  248.0  320.623627  208.779297  28.125036   
218  234.740234  18.878902  120.0  248.0  356.412994  205.990234  28.555864   
219  235.222656  18.452356  120.0  248.0  340.489502  206.657227  28.295830   
220  234.589844  18.823494  120.0  248.0  354.323975  205.105469  28.417585   

     min_g  max_g       var_g  ...  max_a       var_a     mean_b1     std_b1  \
0     88.0  252.0  836.505493  ...  184.0  195.336441  151.947266  13.830170   
1    104.0  252.0  848.567749  ...  181.0  158.647980  150.912598  13.704334   
2    108.0  252.0  851.233826  ...  179.0  142.217026  150.710449  13.569794   
3     96.0  252.0  857.278198  ...  181.0  165.136703  151.036865  13.638016   
4    136.0  252.0  576.071899  ...  169.0   79.725052  148.221191  13.881875   
..     ...    ...         ...  ...    ...         ...         ...        ...   
216  100.0  252.0  765.398743  ...  182.0   93.706268  142.972900  15.570264   
217   96.0  252.0  791.017700  ...  182.0   98.448662  143.115967  15.679187   
218   92.0  252.0  815.437378  ...  186.0  103.035614  143.178223  15.713095   
219   96.0  252.0  800.653992  ...  182.0  101.630920  143.342773  15.722949   
220   92.0  252.0  807.559204  ...  184.0  104.150536  143.385986  15.706528   

     min_b1  max_b1      var_b1  Target   temp  humidity  
0     124.0   190.0  191.273590     0.0  40.88     43.90  
1     125.0   197.0  187.808762     0.0  41.33     43.35  
2     127.0   196.0  184.139297     0.0  42.15     41.65  
3     126.0   194.0  185.995468     0.0  42.97     40.73  
4     127.0   200.0  192.706451     0.0  43.31     40.39  
..      ...     ...         ...     ...    ...       ...  
216   118.0   195.0  242.433105     2.0  49.36     28.55  
217   119.0   194.0  245.836899     2.0  49.42     28.64  
218   118.0   193.0  246.901337     2.0  49.59     28.57  
219   119.0   195.0  247.211121     2.0  49.76     28.42  
220   119.0   193.0  246.695007     2.0  49.83     28.35  

[221 rows x 48 columns]

In [4]:
y = df['Target']
df.drop('Target', axis=1, inplace=True)
x = df
print(x.shape,y.shape)

(221, 47) (221,)


In [5]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)
print(x_train.shape,y_train.shape,x_test.shape,y_test.shape)

(176, 47) (176,) (45, 47) (45,)


In [6]:
scaler = MinMaxScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [7]:
x_train

array([[0.95993092, 0.287324  , 0.65      , ..., 0.51709451, 0.40749022,
        0.56776829],
       [0.86491539, 0.58589643, 0.55      , ..., 0.59744312, 0.38960313,
        0.65985889],
       [0.99866912, 0.03182273, 0.9       , ..., 0.07977243, 0.84740078,
        0.0571853 ],
       ...,
       [0.84937258, 0.59531395, 0.5       , ..., 0.81037419, 0.67411962,
        0.24619384],
       [0.28108562, 0.86076983, 0.15      , ..., 0.43455524, 0.24874231,
        0.61047159],
       [0.92585081, 0.40205065, 0.45      , ..., 0.71363325, 0.85969816,
        0.04678797]])

In [8]:
from tensorflow.keras import Sequential
model = Sequential()
model.add(tf.keras.Input(shape=(47,)))
model.add(tf.keras.layers.Dense(40,activation='relu'))
model.add(tf.keras.layers.Dense(20,activation='relu'))
model.add(tf.keras.layers.Dropout(0.25))
model.add(tf.keras.layers.Dense(3,activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 40)                1920      
                                                                 
 dense_1 (Dense)             (None, 20)                820       
                                                                 
 dropout (Dropout)           (None, 20)                0         
                                                                 
 dense_2 (Dense)             (None, 3)                 63        
                                                                 
Total params: 2,803
Trainable params: 2,803
Non-trainable params: 0
_________________________________________________________________


In [9]:
model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0005),
    metrics=["accuracy"],
)

In [10]:
model.fit(x_train, y_train, batch_size=32, epochs=100, validation_split=0.2)
test_score = model.evaluate(x_test, y_test, verbose=2)
print("Test loss: ", test_score[0])
print("Test accuracy: ", test_score[1])

Epoch 1/100


/usr/local/lib/python3.9/dist-packages/keras/backend.py:5585: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


5/5 [==============================] - 1s 57ms/step - loss: 1.1223 - accuracy: 0.3643 - val_loss: 1.1278 - val_accuracy: 0.3056
Epoch 2/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0827 - accuracy: 0.3786 - val_loss: 1.0866 - val_accuracy: 0.3611
Epoch 3/100
5/5 [==============================] - 0s 9ms/step - loss: 1.0831 - accuracy: 0.4000 - val_loss: 1.0526 - val_accuracy: 0.5556
Epoch 4/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0477 - accuracy: 0.4643 - val_loss: 1.0282 - val_accuracy: 0.5833
Epoch 5/100
5/5 [==============================] - 0s 12ms/step - loss: 1.0551 - accuracy: 0.4500 - val_loss: 1.0123 - val_accuracy: 0.6111
Epoch 6/100
5/5 [==============================] - 0s 10ms/step - loss: 1.0291 - accuracy: 0.4500 - val_loss: 1.0002 - val_accuracy: 0.7222
Epoch 7/100
5/5 [==============================] - 0s 11ms/step - loss: 0.9983 - accuracy: 0.5643 - val_loss: 0.9906 - val_accuracy: 0.6944
Epoch 8/100
5/5 [================

In [11]:
print(model.trainable_variables)

[<tf.Variable 'dense/kernel:0' shape=(47, 40) dtype=float32, numpy=
array([[ 0.12600282, -0.00135313,  0.15594317, ...,  0.02367239,
         0.13093822, -0.16340701],
       [-0.05428009, -0.0204363 ,  0.05891367, ..., -0.20016214,
        -0.1144104 ,  0.09817024],
       [-0.22036445,  0.20556258,  0.17142065, ...,  0.02698986,
        -0.13604717,  0.17504156],
       ...,
       [ 0.04875286, -0.15716554, -0.24942043, ..., -0.04719989,
        -0.1815308 ,  0.0235703 ],
       [ 0.23390779, -0.12590724, -0.18199353, ..., -0.1562478 ,
         0.22930604, -0.18324648],
       [-0.00424905,  0.0217471 , -0.0603998 , ...,  0.12863041,
        -0.16750632,  0.27824193]], dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(40,) dtype=float32, numpy=
array([ 5.90957664e-02,  4.28126864e-02, -1.11413179e-02, -3.48014571e-03,
       -6.40727952e-03,  3.90468836e-02,  1.13481944e-02,  3.37628610e-02,
        3.45006287e-02,  3.23052667e-02,  8.67461599e-03,  0.00000000e+00,
        1.71331

In [12]:
! pip install -q tensorflow-model-optimization

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 238.9/238.9 KB 9.7 MB/s eta 0:00:00


In [13]:
import tensorflow_model_optimization as tfmot

quantize_model = tfmot.quantization.keras.quantize_model

# q_aware stands for for quantization aware.
q_aware_model = quantize_model(model)

# `quantize_model` requires a recompile.
q_aware_model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

q_aware_model.summary()

Instructions for updating:
Lambda fuctions will be no more assumed to be used in the statement where they are used, or at least in the same block. https://github.com/tensorflow/tensorflow/issues/56089


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 quantize_layer (QuantizeLay  (None, 47)               3         
 er)                                                             
                                                                 
 quant_dense (QuantizeWrappe  (None, 40)               1925      
 rV2)                                                            
                                                                 
 quant_dense_1 (QuantizeWrap  (None, 20)               825       
 perV2)                                                          
                                                                 
 quant_dropout (QuantizeWrap  (None, 20)               1         
 perV2)                                                          
                                                                 
 quant_dense_2 (QuantizeWrap  (None, 3)                6

In [14]:
q_aware_model.fit(x_train, y_train, batch_size=32, epochs=1, validation_split=0.2)
test_score = q_aware_model.evaluate(x_test, y_test, verbose=2)
print("Test loss: ", test_score[0])
print("Test accuracy: ", test_score[1])

5/5 [==============================] - 2s 69ms/step - loss: 0.4265 - accuracy: 0.8429 - val_loss: 0.3781 - val_accuracy: 0.8333
2/2 - 0s - loss: 0.3227 - accuracy: 0.9333 - 29ms/epoch - 15ms/step
Test loss:  0.32272839546203613
Test accuracy:  0.9333333373069763


In [15]:
_, baseline_model_accuracy = model.evaluate(
    x_test, y_test, verbose=0)

_, q_aware_model_accuracy = q_aware_model.evaluate(
   x_test, y_test, verbose=0)

print('Baseline test accuracy:', baseline_model_accuracy)
print('Quant test accuracy:', q_aware_model_accuracy)

Baseline test accuracy: 0.8888888955116272
Quant test accuracy: 0.9333333373069763


In [16]:
converter = tf.lite.TFLiteConverter.from_keras_model(q_aware_model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

quantized_tflite_model = converter.convert()

/usr/local/lib/python3.9/dist-packages/tensorflow/lite/python/convert.py:765: UserWarning: Statistics for quantized inputs were expected, but not specified; continuing anyway.
  warnings.warn("Statistics for quantized inputs were expected, but not "


In [ ]:
# Save the model.
with open('model.tflite', 'wb') as f:
  f.write(quantized_tflite_model)

In [ ]:
pd.DataFrame(x_test).to_csv('x_test.csv', index=False)

In [ ]:
pd.DataFrame(y_test).to_csv('y_test.csv', index = False)

In [ ]:
x_train.dtype

dtype('float64')